# Generated by Django 5.2.4 on 2025-07-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_image_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
    ]
