# Generated by Django 5.2.4 on 2025-07-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_cart_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tax',
        ),
    ]
