# Generated by Django 5.2.4 on 2025-07-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_joblisting_paybill_realestatelisting_servicelisting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paybill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='paybill',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='realestatelisting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='realestatelisting',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='servicelisting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servicelisting',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='JobListing',
        ),
        migrations.DeleteModel(
            name='Paybill',
        ),
        migrations.DeleteModel(
            name='RealEstateListing',
        ),
        migrations.DeleteModel(
            name='ServiceListing',
        ),
        migrations.DeleteModel(
            name='VehicleListing',
        ),
    ]
