# Generated by Django 5.2.4 on 2025-07-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_tax_order_service_fee_order_tax_orderitem_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tax',
        ),
    ]
