# Generated by Django 5.2.4 on 2025-08-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_options_alter_order_initial_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('product', 'Product'), ('listing', 'Listing')], default='product', max_length=20),
        ),
    ]
