# Generated by Django 5.2.4 on 2025-08-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='cover_image',
            new_name='image',
        ),
    ]
