# Generated by Django 5.2.4 on 2025-08-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_category_order'),
    ]

    operations = [
    ]
