# Generated by Django 5.2.4 on 2025-08-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_bundle_loyaltyprogram_notificationtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
