# Generated by Django 5.2.4 on 2025-08-24 16:03

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_loyaltyprogram_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquirer_name', models.CharField(max_length=100)),
                ('inquirer_email', models.EmailField(max_length=254)),
                ('inquirer_phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('vendor_response', models.TextField(blank=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific fields'),
        ),
        migrations.AddField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs'),
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('rental', 'Rental'), ('real_estate', 'Real Estate'), ('vehicle', 'Vehicle'), ('job', 'Job'), ('event', 'Event'), ('other', 'Other')], default='service', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='meta_description',
            field=models.TextField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='listing',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Per Hour'), ('daily', 'Per Day'), ('monthly', 'Per Month'), ('yearly', 'Per Year'), ('negotiable', 'Negotiable')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief summary for search results', max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold', 'Sold'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_listings', to='store.category'),
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL'),
        ),
        migrations.AddField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['vendor', '-created_at'], name='store_listi_vendor__a95fca_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'status'], name='store_listi_categor_4eb4a3_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location', 'status'], name='store_listi_locatio_d515e2_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-views_count'], name='store_listi_views_c_bf96b4_idx'),
        ),
        migrations.AddField(
            model_name='listingfavorite',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='store.listing'),
        ),
        migrations.AddField(
            model_name='listingfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.listing'),
        ),
        migrations.AddField(
            model_name='listinginquiry',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='store.listing'),
        ),
        migrations.AlterUniqueTogether(
            name='listingfavorite',
            unique_together={('user', 'listing')},
        ),
    ]
